### ISSUE TITLE
Crash 1.8 manually built

### ISSUE THREAD

**Issue by Kosti1** [hilburn/NotEnoughResources#48]
// Ooh. Shiny.

Time: 27.5.2015 14:26
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.util.StatCollector.translateToLocal(Ljava/lang/String;)Ljava/lang/String;
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:529)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.StatCollector.translateToLocal(Ljava/lang/String;)Ljava/lang/String;
	at neresources.utils.TranslationHelper.translateToLocal(TranslationHelper.java:9)
	at neresources.config.ConfigHandler.loadConfig(ConfigHandler.java:39)
	at neresources.config.ConfigHandler.init(ConfigHandler.java:24)
	at neresources.NEResources.preInit(NEResources.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:527)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (i386) version 3.13.0-53-generic
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Server VM (mixed mode), Oracle Corporation
	Memory: 107694216 bytes (102 MB) / 265588736 bytes (253 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 5 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.99.18.1419 Minecraft Forge 11.14.1.1419 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{8.99.18.1419} [Forge Mod Loader] (forge-1.8-11.14.1.1419.jar) Unloaded->Constructed->Pre-initialized
	Forge{11.14.1.1419} [Minecraft Forge] (forge-1.8-11.14.1.1419.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) Unloaded->Constructed->Pre-initialized
	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.8-0.1.0-ManuallyBuilt.jar) Unloaded->Constructed->Errored
	Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) Unloaded->Constructed->Pre-initialized
	wailafeatures{0.0.1} [WAILA Features] (WAILA-features-1.8-0.0.1.jar) Unloaded->Constructed->Pre-initialized
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 10.1.3' Renderer: 'Gallium 0.4 on AMD CAICOS'
[14:26:44] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:571]: #@!@# Game crashed! Crash report saved to: #@!@# /home/[ITS A SECRET]/.minecraft/crash-reports/crash-2015-05-27_14.26.44-client.txt

I compiled by deleting all but Minecraft, CompatBase.java and Compatibility.java from neresources.compatibility

**Comment by hilburn** [comment]
You know what? I am in no way surprised that this does not work for 1.8.
Because minecraft versions are not compatible with each other.
If you want to modify it to work for 1.8 you are very welcome to do so - but this is not an issue I have any desire or need to fix
