### ISSUE TITLE
Not works with KCauldron without Forestry

### ISSUE THREAD

**Issue by BlazingGamer** [hilburn/NotEnoughResources#64]
When I try to launch KCauldron (forge 1448) with NEResources (0.1.0.120) and bunch of mods (no forestry) i get following error:

[latest.log.txt](https://github.com/hilburn/NotEnoughResources/files/52936/latest.log.txt)

When I looked that log I saw NEResources is using Forestry Classes but they aren't included in! Please fix!

**Comment by BlazingGamer** [comment]
Just copy of log:
[22:17:16] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: forestry/core/blocks/BlockResourceOre
	at neresources.utils.ModList.<clinit>(ModList.java:32) ~[ModList.class:?]
	at neresources.utils.WorldEventHelper.onWorldLoad(WorldEventHelper.java:16) ~[WorldEventHelper.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_121_WorldEventHelper_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1448.133]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:1.7.10-1448.133]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: forestry.core.blocks.BlockResourceOre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 9 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 9 more
[22:17:16] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ClassNotFoundException: forestry.core.blocks.BlockResourceOre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at neresources.utils.ModList.<clinit>(ModList.java:32) ~[ModList.class:?]
	at neresources.utils.WorldEventHelper.onWorldLoad(WorldEventHelper.java:16) ~[WorldEventHelper.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_121_WorldEventHelper_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1448.133]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:1.7.10-1448.133]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	... 11 more
[22:17:16] [Server thread/ERROR]: This crash report has been saved to: C:\Users\ָפנטע 6455\AppData\Roaming\Cauldron-Based\.\crash-reports\crash-2015-12-05_22.17.16-server.txt
[22:17:16] [Server thread/INFO]: Applying holder lookups
[22:17:16] [Server thread/INFO]: Holder lookups applied
[22:17:16] [Server thread/INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by BlazingGamer** [comment]
Just copy of log:
[22:17:16] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: forestry/core/blocks/BlockResourceOre
	at neresources.utils.ModList.<clinit>(ModList.java:32) ~[ModList.class:?]
	at neresources.utils.WorldEventHelper.onWorldLoad(WorldEventHelper.java:16) ~[WorldEventHelper.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_121_WorldEventHelper_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1448.133]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:1.7.10-1448.133]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: forestry.core.blocks.BlockResourceOre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 9 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	... 9 more
[22:17:16] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ClassNotFoundException: forestry.core.blocks.BlockResourceOre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at neresources.utils.ModList.<clinit>(ModList.java:32) ~[ModList.class:?]
	at neresources.utils.WorldEventHelper.onWorldLoad(WorldEventHelper.java:16) ~[WorldEventHelper.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_121_WorldEventHelper_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1448.133]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:1.7.10-1448.133]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:442) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	... 11 more
[22:17:16] [Server thread/ERROR]: This crash report has been saved to: C:\Users\ָפנטע 6455\AppData\Roaming\Cauldron-Based\.\crash-reports\crash-2015-12-05_22.17.16-server.txt
[22:17:16] [Server thread/INFO]: Applying holder lookups
[22:17:16] [Server thread/INFO]: Holder lookups applied
[22:17:16] [Server thread/INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
(I left only crash report part ;)

**Comment by way2muchnoise** [comment]
Post log s using paste bin or alike don't just paste them here.
Well the forestry support should never be loaded when you don't have forestry. So either you have something stealing its modID or KCauldron is messing up.

**Comment by way2muchnoise** [comment]
@BlazingGamer I can launch fine without forestry installed on a pure forge environment.
So I'm going to have to call it a KCauldron problem which this project never supported.
Unless you can come up with something your self or let the KCauldron devs know there isn't much I can do

**Comment by way2muchnoise** [comment]
@BlazingGamer Cancel the last update, I found some issues on my end.

**Comment by BlazingGamer** [comment]
So, I looked at Jenkins and saw that last 9 builds were unsuccessful. Seems thats right :) Thanks for your advices!

**Comment by BlazingGamer** [comment]
Works well with Build 111)

**Comment by way2muchnoise** [comment]
There is an issue with the build server and the amount of backwards compat we have (tons of duplicate libs). The issue was with the classes loading in 9ebb9649abfd0455f8eff5747ef609c3aefac444 I moved some init to be reflective and that fixes the issues.

**Comment by way2muchnoise** [comment]
I would appreciated if you tried the new build once curse accepts it (http://minecraft.curseforge.com/projects/notenoughresources/files/2269453)
